USE [master]
GO

/****** Object:  Database [Genesis]    Script Date: 1/6/2019 17:51:04 ******/
CREATE DATABASE [Genesis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Genesis', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Genesis.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Genesis_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Genesis_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Genesis] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Genesis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Genesis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Genesis] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Genesis] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Genesis] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Genesis] SET ARITHABORT OFF 
GO

ALTER DATABASE [Genesis] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Genesis] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Genesis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Genesis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Genesis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Genesis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Genesis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Genesis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Genesis] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Genesis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Genesis] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Genesis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Genesis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Genesis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Genesis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Genesis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Genesis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Genesis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Genesis] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Genesis] SET  MULTI_USER 
GO

ALTER DATABASE [Genesis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Genesis] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Genesis] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Genesis] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Genesis] SET  READ_WRITE 
GO


